name: request-logger

services:
  api:
    container_name: request-logger.api
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      TYPE: www
    volumes:
      - './:/var/www/app'
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.request-logger=true"
        - "traefik.http.routers.request-logger.tls=true"
        - "traefik.http.routers.request-logger.entrypoints=https"
    networks:
      - web

networks:
  web:
    name: traefik-web
    external: true
