name: request-logger

services:
  api:
    container_name: request-logger.api
    build:
      context: ./
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      TYPE: www
    volumes:
      - './:/var/www/app'
    ports:
      - "80:80"
